# -*- coding: utf-8 -*-
"""#10 Pers_Garis_Tegak_Lurus.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w_71jxavSuXPuJSQB_Np4vlFefxAgRvy
"""

#10 Perpendicular Bisector

def pers_garis_lurus(x1, y1, x2, y2):
  MidX = (x1 + x2) / 2
  MidY = (y1 + y2) / 2
  m = (y2 - y1) / (x2 - x1)
  gradien_garis_lurus = (-1 / m)
  b = MidY - gradien_garis_lurus * MidX
  return gradien_garis_lurus, b

def main():
  x1 = float(input("masukkan nilai x1"))
  y1 = float(input("masukkan nilai y1"))
  x2 = float(input("masukkan nilai x2"))
  y2 = float(input("masukkan nilai y2"))

  gradien_garis_lurus, b = pers_garis_lurus(x1, y1, x2, y2)

  persamaan_garis_lurus = (f"y = {gradien_garis_lurus}x + {b} ")
  print(persamaan_garis_lurus)

if __name__ == "__main__":
  main()