# -*- coding: utf-8 -*-
"""#12 Fighter Jet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w_71jxavSuXPuJSQB_Np4vlFefxAgRvy
"""

#12 Fighter Jet

def hitung_akselerasi(kecepatan_akhir, distance):
  kecepatan_akhir_cnvrt = (kecepatan_akhir * (1000/3600))
  akselerasi = (kecepatan_akhir_cnvrt ** 2) / (2 * distance)
  return akselerasi, kecepatan_akhir_cnvrt

def main():
  kecepatan_akhir = float(input("masukkan kecepatan akhir sebelum takeoff dalam (km/hr)"))
  distance = float(input("masukkan jarak yang ditempuh dalam (m)"))

  akselerasi_akhir, kecepatan_akhir_cnvrt = hitung_akselerasi(kecepatan_akhir, distance)

  kecepatan_awal = 0
  time = (kecepatan_akhir_cnvrt - kecepatan_awal) / akselerasi_akhir

  print(f"akselerasi pesawat tersebut adalah {akselerasi_akhir:.2f} meter per detik,")
  print(f"dengan waktu yang dibutuhkan untuk mencapai kecepatan saat takeoff adalah {time:.2f} detik")

if __name__ == "__main__":
  main()