# -*- coding: utf-8 -*-
"""#2 Hydroelectric dam.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w_71jxavSuXPuJSQB_Np4vlFefxAgRvy
"""

#2 Hydroelectric Dam

def dam(height1, flow):
  grav = 9.80
  massa_air = flow * 1000
  Work = massa_air * grav * height1
  return Work

def main():
  height1 = float(input("what's the height of the dam? dalam (m)"))
  flow = float(input("what's the flow rate of the dam? (contoh: 1.30e3 untuk 1.30 x 10^3 (m^3/s)"))

  Work = dam(height1, flow)
  efisiensi = 0.90
  Work_eff = Work * efisiensi

  Work_eff_MW = Work_eff / 10**6

  print(f"Daya yang dihasilkan adalah {Work_eff_MW:.2f} Megawatt")

if __name__ == "__main__":
  main()