# -*- coding: utf-8 -*-
"""#4 Us Dollars to Pounds.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w_71jxavSuXPuJSQB_Np4vlFefxAgRvy
"""

#4 US dollars to Pounds
def main(usd_amount):
  convert_rate = 0.65
  gbp_amount = usd_amount * convert_rate
  return gbp_amount
usd_amount = float(input("How much do you want to convert to GBP?:"))
gbp_amount = main(usd_amount)
print(f"{usd_amount} USD is equal to {gbp_amount} GBP")