# -*- coding: utf-8 -*-
"""#6 Final_Score.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w_71jxavSuXPuJSQB_Np4vlFefxAgRvy
"""

#6 Calculate Final Score
def calculate_final_score(desired_grade, minimum_avg, current_avg, weight_final):
  current_weight = 1 - (weight_final / 100)

  final_score_needed = (minimum_avg - (current_avg * current_weight)) / (weight_final / 100)
  return final_score_needed

def main():
  desired_grade = input("Enter Desired Grade")
  minimum_avg = float(input("Enter Minimum Average Required"))
  current_avg = float(input("Enter Current Average in Course"))
  weight_final = float(input("Enter how much of the final counts as a percentage of the course grade"))

  final_score_needed = calculate_final_score(desired_grade, minimum_avg, current_avg, weight_final)

  print(f"You need a score of {final_score_needed:.2f} on the final to get a {desired_grade}")

if __name__ == "__main__":
  main()