# -*- coding: utf-8 -*-
"""#8 Toilet_Plan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w_71jxavSuXPuJSQB_Np4vlFefxAgRvy
"""

#8 Metro City Planners

populasi = int(input("Berapa banyak populasi dalam komunitas anda?"))
byk_toilet_lama = populasi / 3
harga_toilet_baru = byk_toilet_lama * 150

rata2_toilet_lama = (15 * byk_toilet_lama) * 14
rata2_toilet_baru = (2 * byk_toilet_lama) * 14
selisih_baru = (rata2_toilet_lama - rata2_toilet_baru)

print(f"Berdasarkan banyak populasi anda, toilet model lama menghabiskan sekitar {round(rata2_toilet_lama)} liter per hari")
print(f"Sedangkan toilet model baru menghabiskan sekitar {round(rata2_toilet_baru)} liter per hari")
print(f"Anda akan mengurangi pengeluaran air sebanyak {round(selisih_baru)} per hari, dengan biaya sebesar {round(harga_toilet_baru)} USD")